### ISSUE TITLE
When training, I meet the problem of "NaN or Inf found in input tensor". Is it a mistake?

### ISSUE THREAD

**Issue by xzm2002** [changwxx/UniOT-for-UniDA#1]

**Comment by changwxx** [comment]
Can you give a more detailed description about the problem you encountered? (e.g. which part of the code would output like that? Which transfer task did you set?)

**Comment by changwxx** [comment]
Can you give a more detailed description about the problem you encountered? (e.g. which part of the code would output like that? Which transfer task did you set?)

**Comment by JunkunPeng17** [comment]
I met the same situation as xzm2002 when I did the transfer task on Product2Art. I also did the other transfer tasks, and they worked well.
![cc4ac167ea1169571027d79dcfb685c](https://user-images.githubusercontent.com/56396894/205017249-e87aa11d-0047-4425-b0de-ecb17958af81.jpg)

**Comment by changwxx** [comment]
I would like to thank @JunkunPeng17 for providing details for this bug! 
I found sometimes the `loss_CCD` would be `NaN` for OfficeHome transfer tasks, since CCD did not find any top-confident common target samples and `high_conf_label_id` is a 0-size tensor.
I have fixed this bug in main.py
https://github.com/changwxx/UniOT-for-UniDA/blob/9ba3bad29956c2f170cd82c9dd8cfa3ae2af3dda/main.py#L170-L176
However, this bug would not lead to performance deterioration, and hence the results reported in the paper are still reliable.
